//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ValidadeRegister {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValidadeRegister.IRegisterValidator")]
    public interface IRegisterValidator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterValidator/ValidateRegister", ReplyAction="http://tempuri.org/IRegisterValidator/ValidateRegisterResponse")]
        string[] ValidateRegister(string[] _cpfs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRegisterValidator/ValidateRegister", ReplyAction="http://tempuri.org/IRegisterValidator/ValidateRegisterResponse")]
        System.Threading.Tasks.Task<string[]> ValidateRegisterAsync(string[] _cpfs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRegisterValidatorChannel : Client.ValidadeRegister.IRegisterValidator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterValidatorClient : System.ServiceModel.ClientBase<Client.ValidadeRegister.IRegisterValidator>, Client.ValidadeRegister.IRegisterValidator {
        
        public RegisterValidatorClient() {
        }
        
        public RegisterValidatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterValidatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterValidatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterValidatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] ValidateRegister(string[] _cpfs) {
            return base.Channel.ValidateRegister(_cpfs);
        }
        
        public System.Threading.Tasks.Task<string[]> ValidateRegisterAsync(string[] _cpfs) {
            return base.Channel.ValidateRegisterAsync(_cpfs);
        }
    }
}
